# Este archivo permite referenciar al contenido del sql para crear las tablas y datos INICIALES de prueba
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-scripts
data:
  init.sh: |
    #!/bin/bash
    sed 's/\r//' /docker-entrypoint-initdb.d/init.sql | mariadb -u root -p"$MARIADB_ROOT_PASSWORD" ic4302
  init.sql: |
{{ .Files.Get "scripts/mariadb_init.sql" | indent 4 }}
{{- end }}